controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Header
parfum: 
    path: /catalogue?categorie=parfum
    controller: App\Controller\CatalogueController::index
    methods: ['GET']

maison: 
    path: /catalogue?categorie=maison
    controller: App\Controller\CatalogueController::index
    methods: ['GET']

muscs: 
    path: /catalogue?categorie=muscs
    controller: App\Controller\CatalogueController::index
    methods: ['GET']

cosmetiques: 
    path: /catalogue?categorie=cosmetiques
    controller: App\Controller\CatalogueController::index
    methods: ['GET']

brumes: 
    path: /catalogue?categorie=brumes
    controller: App\Controller\CatalogueController::index
    methods: ['GET']

capillaires: 
    path: /catalogue?categorie=capillaires
    controller: App\Controller\CatalogueController::index
    methods: ['GET']


# Accueil
accueil:
    path: /
    controller: App\Controller\DefaultController::index
    methods: ['GET']

# Génération Base données
insertion_base_index:
    path: /insertion/base
    controller: App\Controller\BackOffice\IndexCreationBaseController.php::index
    methods: ['GET']

insertion_base_all:
    path: /insertion/base/all
    controller: App\Controller\BackOffice\MainInsertionController.php::index
    methods: ['GET']

# Catalogue
catalogue:
    path: /catalogue
    controller: App\Controller\CatalogueController::index
    methods: ['GET']

# Paiemment
payment_list:
    path: /payment
    controller: App\Controller\PayController::index
