controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil:
    path: /
    controller: App\Controller\DefaultController::index
    methods: ['GET']