controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Accueil
accueil:
    path: /
    controller: App\Controller\DefaultController::index
    methods: ['GET']

# Génération Base données
insertion_base_index:
    path: /insertion/base
    controller: App\Controller\BackOffice\IndexCreationBaseController.php::index
    methods: ['GET']

insertion_base_all:
    path: /insertion/base/all
    controller: App\Controller\BackOffice\MainInsertionController.php::index
    methods: ['GET']

# Paiemment
payment_list:
    path: /payment
    controller: App\Controller\PayController::index
